spring:
  application:
    name: pmpSDK



  datasource:
    url: jdbc:opengauss://47.113.224.195:5432/postgres
    username: gaussdb
    password: MyPassword@123
    driver-class-name: org.opengauss.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  mapper-locations: classpath*:/mapper/**/*.xml

server:
  port: 8083


logging:
  level:
    com.pmpsdk: INFO
    com.pmpsdk.client.QGAPIClient: DEBUG
    com.pmpsdk.util.QGLogger: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/pmp-sdk.log



qgpmpsdk:
     client:
       access-key: "your_access_key_123"
       secret-key: "your_secret_key_abc"
       project-token: "your_project_token_123"
       sentry-url: "your_sentry_url_123"
       api-base-url: "your_api_base_url_123"
       environment: "666"